Issue 414
3drepo/3drepobouncer pull request #425
Opened 2021-01-18 09:15 UTC by sebjf

This addresses #414, to support https://github.com/3drepo/3drepounity/issues/322. It modifies the bouncer to include the primitive type of mesh nodes (falling back to triangles, if none is set). Additionally, the AssetModelExport and MeshMapReorganiser classes have been modified to support face limits and to allow the Unity BouncerWrapper to read the primitive type.

2021-01-22 13:24 UTC, carmenfan requested changes
@sebjf  can we also add some unit tests on the meshnode type? e.g. ensure that repo_bson_factory calculates the correct type given the indices, meshNode will return the right type, etc)

2021-02-01 11:51 UTC, sebjf commented on bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
> +				if (nIndices == 3) {
Corrected in 9b8bc97b59e8b5effd4029ca880fea2883cbf481

2021-02-01 11:52 UTC, sebjf commented on bouncer/src/repo/core/model/bson/repo_node_mesh.h
> +				* Get the mesh primitive type (points, lines, triangles, quads) as a string (triangles if not set).
Corrected in 9b8bc97b59e8b5effd4029ca880fea2883cbf481

2021-02-01 11:58 UTC, sebjf commented on bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
> +				if (primitive == MeshNode::Primitive::UNKNOWN)
This end if statement is intentionally separate; this code block attempts to infer the primitive type if it's not already set. The statements above attempt to recover one of two types (that we support, lines or triangles) and the last statement checks if they were successful or not (I've put some comments in a9b6f330aac2e237652aa8e2db8a3225601f7958 for this!)

2021-02-01 12:05 UTC, carmenfan commented on bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
> +				if (primitive == MeshNode::Primitive::UNKNOWN)
the code only enters this part if primitive is unknown, we attempt to set it at L407 and L413. so for the primitive to still be unknown at this point, it means both L407 and L413 were evaluated to false, so this should just be an else?

In other words, there's no situation where L407 or L410 evaluated to true would enter this condition, and there's no way the primitive is set to something other than unknown if they were evaluated to false. 

I don't quite get why it needs to be an if, I feel like I'm missing something 😆

2021-02-01 12:44 UTC, sebjf commented on bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
> +				if (primitive == MeshNode::Primitive::UNKNOWN)
Ah yes you are right! I'll update it...

2021-02-01 12:47 UTC, sebjf commented on bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
> +				if (primitive == MeshNode::Primitive::UNKNOWN)
Took a sec to see past my preconceived design, but updated in 7c13f2e2dc0e840d093d33c9ab2a5cbb74b7c3e1!

2021-02-01 13:54 UTC, sebjf commented
@carmenfan I have added some unit tests for the MeshNode with Lines primitives. Let me know how they look/if you want more thorough tests, error cases, etc!

2021-02-18 17:12 UTC, carmenfan approved these changes

2021-02-23 11:56 UTC, merged