[WIP] ISSUE #485 Absorb the bouncer wrapper code and add option to build alongside bouncer
3drepo/3drepobouncer pull request #486
Opened 2021-08-03 14:59 UTC by har00n-haider

This fixes #485 

## Description

## Test cases

2021-08-05 13:50 UTC, har00n-haider commented
@carmenfan travis is failing on the 3drepobouncerwrapperTest due to a segfault. Good news is I guess it found the executable!

On my local machine the tests pass with a fresh restore of the db from tests. Could be that the 3drepobouncerTest is making changes to the db that the 3drepobouncerwrapperTest is not expecting? I am running that scenario on my local machine atm.

Do you think its worth me testing this locally in linux VM? Or maybe just rerunning on travis with some more debug messages in the test itself...

2021-08-05 14:12 UTC, carmenfan commented
> @carmenfan travis is failing on the 3drepobouncerwrapperTest due to a segfault. Good news is I guess it found the executable!
> 
> On my local machine the tests pass with a fresh restore of the db from tests. Could be that the 3drepobouncerTest is making changes to the db that the 3drepobouncerwrapperTest is not expecting? I am running that scenario on my local machine atm.
> 
> Do you think its worth me testing this locally in linux VM? Or maybe just rerunning on travis with some more debug messages in the test itself...


it's probably worth sorting out the failures before investigating on the seg fault. Could the seg fault be that you make assumptions of previous function call gives you valid data so it becomes corrupted when you make that assumption as you carry on? if that's the case you might want to use ASSERT_TRUE or ASSERT_EQ instead of EXPECT so the test just ends if any of the assertions were not met

2021-08-06 09:28 UTC, carmenfan requested changes

2021-08-18 13:48 UTC, carmenfan approved these changes

2021-08-18 13:50 UTC, carmenfan approved these changes

2021-08-18 13:51 UTC, carmenfan commented
@keifgwinn  about to merge this in. just FYI after this is merged the bouncerwrapper is going to be compiled as part of 3drepobouncer (along with Client etc)

so there shouldn't be a need to run the CMAKE stuff on the unity build (it will still need the built binaries from the bouncer compilation to work)

2021-08-18 14:21 UTC, merged