Update repo_ifc_utils_geometry_handler.cpp
3drepo/3drepobouncer pull request #650
Opened 2023-10-27 13:47 UTC by sbanethia

ISSUE #590 Changes for viewing 2D lines in 3Drepo when and IFC file is uploaded.

This fixes #590 

#### Description
By this changes user can view 2D lines in the 3drepo when he uploads IFC file.

2023-10-27 17:10 UTC, carmenfan requested changes
Trying it on other models - the lines don't seem to be at the right place:
![image](https://github.com/3drepo/3drepobouncer/assets/11945337/55719456-e2c0-4275-9b53-2241da48fba4)

![image](https://github.com/3drepo/3drepobouncer/assets/11945337/6e17f843-d734-4306-8e8d-07b927d136d5)

![image](https://github.com/3drepo/3drepobouncer/assets/11945337/0b8b86f0-9da0-4834-a622-4f11095e292a)


You can find the files here: https://asitesol.sharepoint.com/:f:/s/3DRepoTeamFolder/EuVtlg-FYNJNkpMTZqV8lbcBfZCSotxkHklEJyqa4SO6cQ?e=WXZR9P

2023-11-10 12:15 UTC, sbanethia commented on ifcUtils/repo_ifc_utils_geometry_handler.cpp
> +	constexpr int data3D = 3;
Changes done.

2023-11-10 12:15 UTC, sbanethia commented on ifcUtils/repo_ifc_utils_geometry_handler.cpp
> +			auto edges = ob_geo->geometry().edges();
Changes done.

2023-11-10 12:16 UTC, sbanethia commented on ifcUtils/repo_ifc_utils_geometry_handler.cpp
> +				if ((primitive == data3D) || (primitive==data2D)) ++matIndIt;
Changes done.

2023-11-10 12:16 UTC, sbanethia commented on ifcUtils/repo_ifc_utils_geometry_handler.cpp
> +				auto matInd = primitive == data3D ? *matIndIt : ob_geo->geometry().materials().size();
Changes done.

2023-11-30 14:21 UTC, carmenfan approved these changes

2023-11-30 16:45 UTC, merged