ISSUE #697 Decomissioned Role, User and Camera types
3drepo/3drepobouncer pull request #700
Opened 2024-09-18 08:19 UTC by sebjf

This fixes #697

#### Description
(This PR exists to run Travis for the moment.)

#### Test cases

2024-09-18 08:48 UTC, sebjf commented
Hi @carmenfan, while on our deleting expedition should we remove GLTFModelExport as well? (Its non-zero cost to maintain because it interacts with the web buffers code, and is very out of date - I was just looking and realised it also relies on .io hosting shaders that are no longer there!)

2024-09-18 08:54 UTC, carmenfan commented
@sebjf I'd say so yes 🙈

2024-09-23 10:00 UTC, carmenfan requested changes
I think we can get rid of the assimp exporter as well

the rest of the comments I leave it up to you 😆 I don't feel like backwards compatibility is too much of a concern since with unity bundles removed we are unlikely to be reading existing data with our current use case for bouncer?

2024-09-24 08:27 UTC, sebjf commented on bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_assimp.cpp
> -
Done!

2024-09-24 08:28 UTC, sebjf commented on bouncer/src/repo/core/model/bson/repo_bson_ref.h
> +					GRIDFS, // GRIDFS is no longer supported but may exist in the database
Done!

2024-09-24 08:33 UTC, sebjf commented on bouncer/src/repo/core/model/repo_model_global.h
> +#define REPO_NODE_TYPE_CAMERA			"camera" // No longer supported in Bouncer but may exist in previous imports
Done!

2024-09-26 10:30 UTC, carmenfan approved these changes

2024-09-26 10:30 UTC, merged