ISSUE #545 updated bouncer worker to use yup
3drepo/3drepobouncer pull request #716
Opened 2024-12-02 17:34 UTC by sebjf

This fixes #545

#### Description
This PR updates `config.js` in `bouncer_worker` so that it uses `yup` to perform basic transforms and validation of the config, instead of us doing it by hand.

The yup schema has been written to match the Readme (which has also had a couple of outdated segments removed), for the parts of the schema that are used by bouncer worker.

The log directories fallback is still done as a post processing step - it is ambigious whether the `default` transformer of yup can use another field as a fallback; the answers online don't seem to work with our version, and its complicated by the fact the fields are not siblings either. For simplicitly, these two fallbacks remain conditionals, with yup validating the types of the fields involved.

Finally, a few packages flagged by dependabot have been updated.

#### Test cases

2024-12-03 12:05 UTC, carmenfan requested changes

2024-12-03 12:05 UTC, carmenfan commented on tools/bouncer_worker/src/lib/config.js
> +	logLocation: string(),
I think logLocation is just old place where we put workerLogPath?

I think we can probably get rid of it

2024-12-03 12:05 UTC, carmenfan commented on tools/bouncer_worker/src/lib/config.js
> +		config = schema.validateSync(config);
can we turn on the option of `stripUnknown`? so whoever wants to add an option will have to make sure they add it in the schema

2024-12-03 13:11 UTC, sebjf commented on tools/bouncer_worker/src/lib/config.js
> +	worker_queue: string(),
I think so. These [conditionally](https://github.com/3drepo/3drepobouncer/blob/5f559069381254d623f00875d424769e2b297c1f/tools/bouncer_worker/src/lib/queueHandler.js#L40) populate the `queueHandlers` object, but this object is simply used as a lookup when the actual queues to listen to are enumerated from the arguments, so there should be no harm in defining them.

2024-12-03 13:22 UTC, carmenfan commented on tools/bouncer_worker/src/lib/config.js
> +			config.instanceId = uuidv4();
Ah I see what you mean... in which case we could leave it as is.

2024-12-04 17:02 UTC, carmenfan approved these changes

2024-12-04 17:34 UTC, merged